spring:
  datasource:
    dynamic:
      primary: users
  # datasource 数据源配置内容
      datasource:
        # 订单数据源配置
        orders:
          url: jdbc:mysql://127.0.0.1:3306/hikari?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 802386
        # 用户数据源配置
        users:
          url: jdbc:mysql://127.0.0.1:3306/hikari1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 802386
  jpa:
    show-sql: true # 打印 SQL 。生产环境，建议关闭
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate:
      ddl-auto: update