spring:
  jpa:
    hibernate:
      ddl-auto: none
  shardingsphere:
    datasource:
      names: ds-orders-0, ds-orders-1,ds-slave-0,ds-slave-1
      ds-orders-0:
        url: jdbc:mysql://192.168.50.10:3306/acnew?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 802386
        type: com.alibaba.druid.pool.DruidDataSource
      ds-orders-1:
        url: jdbc:mysql://192.168.50.10:3306/acold?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 802386
        type: com.alibaba.druid.pool.DruidDataSource
      ds-slave-0:
        url: jdbc:mysql://192.168.50.10:3307/acnew?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 802386
        type: com.alibaba.druid.pool.DruidDataSource
      ds-slave-1:
        url: jdbc:mysql://192.168.50.10:3307/acold?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 802386
        type: com.alibaba.druid.pool.DruidDataSource
    sharding:
      tables:
        orders:
          actualDataNodes: ds-orders-01.orders_$->{[0,2,4,6]}, ds-orders-11.orders_$->{[1,3,5,7]}
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              algorithm-expression: ds-orders-$->{user_id%2}
              sharding-column: user_id
          table-strategy:
            inline:
              algorithm-expression: orders_$->{user_id%8}
              sharding-column: user_id
        order_config:
          actualDataNodes: ds-orders-01.order_config
      master-slave-rules:
        ds-orders-01:
          master-data-source-name: ds-orders-0
          slave-data-source-names: ds-slave-0
        ds-orders-11:
          master-data-source-name: ds-orders-1
          slave-data-source-names: ds-slave-1
    props:
      sql:
        show: true